# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Handshake

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Handshake(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Handshake()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandshake(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Handshake
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Handshake
    def Endpoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Handshake
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Handshake
    def HeartbeatFreq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HandshakeStart(builder): builder.StartObject(3)
def Start(builder):
    return HandshakeStart(builder)
def HandshakeAddEndpoint(builder, endpoint): builder.PrependUint8Slot(0, endpoint, 0)
def AddEndpoint(builder, endpoint):
    return HandshakeAddEndpoint(builder, endpoint)
def HandshakeAddPort(builder, port): builder.PrependUint16Slot(1, port, 0)
def AddPort(builder, port):
    return HandshakeAddPort(builder, port)
def HandshakeAddHeartbeatFreq(builder, heartbeatFreq): builder.PrependUint32Slot(2, heartbeatFreq, 0)
def AddHeartbeatFreq(builder, heartbeatFreq):
    return HandshakeAddHeartbeatFreq(builder, heartbeatFreq)
def HandshakeEnd(builder): return builder.EndObject()
def End(builder):
    return HandshakeEnd(builder)