# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Pad

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ButtonsData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # ButtonsData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ButtonsData
    def Select(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ButtonsData
    def Start(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # ButtonsData
    def Up(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # ButtonsData
    def Right(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))
    # ButtonsData
    def Down(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ButtonsData
    def Left(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5))
    # ButtonsData
    def Lt(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # ButtonsData
    def Rt(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(7))
    # ButtonsData
    def Triangle(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ButtonsData
    def Circle(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(9))
    # ButtonsData
    def Cross(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # ButtonsData
    def Square(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))

def CreateButtonsData(builder, select, start, up, right, down, left, lt, rt, triangle, circle, cross, square):
    builder.Prep(1, 12)
    builder.PrependBool(square)
    builder.PrependBool(cross)
    builder.PrependBool(circle)
    builder.PrependBool(triangle)
    builder.PrependBool(rt)
    builder.PrependBool(lt)
    builder.PrependBool(left)
    builder.PrependBool(down)
    builder.PrependBool(right)
    builder.PrependBool(up)
    builder.PrependBool(start)
    builder.PrependBool(select)
    return builder.Offset()
