# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Pad

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MotionData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # MotionData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MotionData
    def Gyro(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # MotionData
    def Accelerometer(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateMotionData(builder, gyro_x, gyro_y, gyro_z, accelerometer_x, accelerometer_y, accelerometer_z):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(accelerometer_z)
    builder.PrependFloat32(accelerometer_y)
    builder.PrependFloat32(accelerometer_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(gyro_z)
    builder.PrependFloat32(gyro_y)
    builder.PrependFloat32(gyro_x)
    return builder.Offset()
